### ISSUE TITLE
error: key "F9F9FA97A403F63E" could not be looked up remotely

### ISSUE THREAD

**Issue by daya-prac** [FZUG/repo#74] opened 2016-03-13 06:14 UTC
```
[user@host ~]$ sudo pacman-key --init
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: Generating pacman keyring master key...
gpg: skipping control `%no-protection' ()
......+++++
...+++++
gpg: key 2275D7B5 marked as ultimately trusted
gpg: Done
==> Updating trust database...
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u


[user@host ~]$ yaourt -S unzip-iconv
resolving dependencies...
looking for conflicting packages...

Packages (1) unzip-iconv-6.0-11

Total Installed Size:  0.32 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#######################] 100%
downloading required keys...
error: key "F9F9FA97A403F63E" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

```

**Comment by sztsian** [comment] 2016-03-13 07:37
duplicate of issue #73

**Comment by sztsian** [comment] 2016-03-22 00:56
Hi @daya-prac , #73 would be closed as "Workaround Provided". Did your problem fixed with the workaround provided there?

**Comment by daya-prac** [comment] 2016-03-23 06:30
@sztsian Yes, fixed. Thinks

**Closed as completed** 2016-03-23 10:53 UTC
Labels: duplicate
