### ISSUE TITLE
Deepin - Broken Dependencies on FC28

### ISSUE THREAD

**Issue by andyrichardson** [FZUG/repo#316] opened 2018-06-10 11:01 UTC
## About
I'm currently trying to get Deepin DE installed on my Fedora 28 build.

## Reproduction
Running the command `dnf install startdde` results in the following error:

```
Problem: conflicting requests
  - nothing provides libgo.so.11()(64bit) needed by startdde-3.1.16-1.fc28.x86_64
```

This is the case with or without the `mosquito/deepin` copr repository enabled.

## Environment
The following files are in my `/usr/lib64` folder:

 - libgo.so.13
 - libgo.so.13.0.0
 - libgo.so.11 >> libgo.so.13  (system link)

**Comment by sztsian** [comment] 2018-06-10 11:08
Thanks for the report. I think you mean with the startdde installed from Fedora repo it also have the same issue, right? If so, will you please file a bug against [bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora)?
Note since we only have three contributors for the Deepin Desktop packaging effort in Fedora, and unfortunately all of us are pretty busy, so a delayed response is expected.

**Comment by andyrichardson** [comment] 2018-06-10 12:19
@sztsian thanks for the quick response. 

I've created a bug report [here](https://bugzilla.redhat.com/show_bug.cgi?id=1589514).

I'd love to try and help (although I'm not exactly experienced in this domain). Is there a repository for building the deepin environment in Fedora/rpm based distros? 

If so, I'll give it a shot trying to update the dependencies to build and run in FC28.

**Comment by sztsian** [comment] 2018-06-10 12:34
> I've created a bug report here.

Thanks!
> I'd love to try and help (although I'm not exactly experienced in this domain). Is there a repository for building the deepin environment in Fedora/rpm based distros?

Basically, the RPM spec file is available here

https://src.fedoraproject.org/rpms/startdde/branch/f28

It's clear that this was caused by dependency issue. So you might try to fix it and send a PR to the above repo/branch. Meanwhile the maintainer did not offer me the write permission yet, so I will ping him offline recently to make him aware of this issue.

**Comment by sztsian** [comment] 2018-12-04 12:49
Right now all the essential Deepin DE packages are in Fedora repo. So I am closing this bug. The Deepin DE will be in a basic usable status since Fedora 30 hopefully.

**Closed as completed by sztsian** 2018-12-04 12:49 UTC
